import { useEffect, useState } from 'react';
import { base44 } from '@/api/base44Client';
import { currentUserName } from '@/lib/useCurrentUser';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
const today=()=>new Date().toISOString().slice(0,10), blank={date:today(),product_id:'',production_order_id:'',produced_quantity:0,loss_quantity:0,leftover_quantity:0,responsible:'',observation:''}, cls='h-9 w-full rounded-md border bg-background px-3 text-sm';
export default function DailyProductionDialog({open,onClose,record,products,orders,onSaved}){
 const [form,setForm]=useState(blank),[saving,setSaving]=useState(false),[error,setError]=useState('');useEffect(()=>{if(open){setForm(record?{...blank,...record}:{...blank,date:today(),responsible:currentUserName()});setError('')}},[open,record]);const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 const orderChange=id=>{const o=orders.find(x=>x.id===id);setForm(x=>({...x,production_order_id:id,product_id:o?.product_id||x.product_id,produced_quantity:o?.planned_quantity||x.produced_quantity}))};
 const save=async()=>{const p=products.find(x=>x.id===form.product_id);if(!p||Number(form.produced_quantity)<=0){setError('Selecione o produto e informe a quantidade produzida.');return}setSaving(true);try{const payload={...form,product_name:p.name,unit:p.yield_unit,produced_quantity:Number(form.produced_quantity),loss_quantity:Number(form.loss_quantity||0),leftover_quantity:Number(form.leftover_quantity||0)};record?await base44.entities.DailyProduction.update(record.id,payload):await base44.entities.DailyProduction.create(payload);if(form.production_order_id)await base44.entities.ProductionOrder.update(form.production_order_id,{status:'concluida',produced_quantity:Number(form.produced_quantity)});onClose();await onSaved()}catch(e){setError(e.message||'Não foi possível salvar.')}finally{setSaving(false)}};
 return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent><DialogHeader><DialogTitle>{record?'Editar controle diário':'Registrar produção diária'}</DialogTitle></DialogHeader><div className="grid sm:grid-cols-2 gap-3"><Field l="Data"><Input type="date" value={form.date} onChange={e=>set('date',e.target.value)}/></Field><Field l="Ordem de produção"><select className={cls} value={form.production_order_id} onChange={e=>orderChange(e.target.value)}><option value="">Sem ordem vinculada</option>{orders.filter(x=>!['concluida','cancelada'].includes(x.status)).map(x=><option key={x.id} value={x.id}>{x.date} — {x.product_name}</option>)}</select></Field><Field l="Produto *"><select className={cls} value={form.product_id} onChange={e=>set('product_id',e.target.value)}><option value="">Selecione</option>{products.filter(x=>x.status==='ativo').map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field l="Quantidade produzida"><Input type="number" min="0.01" step="0.01" value={form.produced_quantity} onChange={e=>set('produced_quantity',e.target.value)}/></Field><Field l="Perdas"><Input type="number" min="0" step="0.01" value={form.loss_quantity} onChange={e=>set('loss_quantity',e.target.value)}/></Field><Field l="Sobras"><Input type="number" min="0" step="0.01" value={form.leftover_quantity} onChange={e=>set('leftover_quantity',e.target.value)}/></Field><Field l="Responsável"><Input value={form.responsible} onChange={e=>set('responsible',e.target.value)}/></Field></div><Field l="Observação"><Input value={form.observation} onChange={e=>set('observation',e.target.value)}/></Field>{error&&<p className="text-sm text-destructive">{error}</p>}<DialogFooter><Button variant="outline" onClick={onClose}>Cancelar</Button><Button onClick={save} disabled={saving}>{saving?'Salvando...':'Registrar'}</Button></DialogFooter></DialogContent></Dialog>;
}
function Field({l,children}){return <div className="space-y-1"><Label className="text-xs">{l}</Label>{children}</div>}