import { useState } from 'react';
import { ChevronDown, Pencil, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { cashDate, cashMoney, channelLabels, entryTotal, exitTotal, statusLabels } from '@/lib/cashMovementUtils';
const Badge = ({ row }) => <span className={`inline-flex rounded-full px-2 py-1 text-xs font-medium ${row.status === 'divergente' ? 'bg-red-50 text-cash-alert' : row.status === 'conferido' ? 'bg-emerald-50 text-cash-positive' : 'bg-slate-100 text-cash-secondary'}`}>{statusLabels[row.status]}</span>;
export default function CashMovementLedger({ rows, onEdit, onDelete }) {
  const [expanded, setExpanded] = useState('');
  if (!rows.length) return <div className="rounded-cash border border-cash-border bg-cash-card p-10 text-center font-body text-sm text-cash-secondary">Nenhum movimento encontrado.</div>;
  return <><div className="hidden overflow-x-auto rounded-cash border border-cash-border bg-cash-card md:block"><table className="w-full min-w-[940px] font-body text-sm"><thead className="bg-cash-surface text-xs uppercase text-cash-secondary"><tr>{['Data','Canal','Operador','Máquinas / contas','Entradas','Saídas','Saldo','Divergência','Status','Ações'].map(h => <th key={h} className="px-4 py-3 text-left font-medium">{h}</th>)}</tr></thead><tbody className="divide-y divide-cash-border">{rows.map(row => <tr key={row.id}><td className="px-4 py-3">{cashDate(row.date)}</td><td className="px-4 py-3">{channelLabels[row.channel] || '—'}</td><td className="px-4 py-3 font-medium">{row.operator_name || '—'}</td><td className="max-w-[220px] truncate px-4 py-3">{row.machine_accounts || '—'}</td><td className="px-4 py-3 font-semibold tabular-nums text-cash-positive">{cashMoney(entryTotal(row))}</td><td className="px-4 py-3 font-semibold tabular-nums text-cash-alert">{cashMoney(exitTotal(row))}</td><td className="px-4 py-3 font-semibold tabular-nums">{cashMoney(row.expected_balance)}</td><td className={`px-4 py-3 font-semibold tabular-nums ${Math.abs(row.difference || 0) > .01 ? 'text-cash-alert' : 'text-cash-positive'}`}>{cashMoney(row.difference)}</td><td className="px-4 py-3"><Badge row={row}/></td><td className="px-4 py-3"><div className="flex gap-1"><Button variant="ghost" size="icon" onClick={() => onEdit(row)} aria-label="Editar"><Pencil/></Button><Button variant="ghost" size="icon" onClick={() => onDelete(row)} className="text-cash-alert" aria-label="Excluir"><Trash2/></Button></div></td></tr>)}</tbody></table></div><div className="space-y-3 md:hidden">{rows.map(row => <article key={row.id} className="rounded-cash border border-cash-border bg-cash-card"><button onClick={() => setExpanded(expanded === row.id ? '' : row.id)} className="flex min-h-11 w-full items-center justify-between gap-3 p-4 text-left"><div><p className="font-display text-sm font-semibold text-cash-text">{cashDate(row.date)} · {row.operator_name || 'Sem operador'}</p><p className="mt-1 font-body text-xs text-cash-secondary">{channelLabels[row.channel]} · Saldo {cashMoney(row.expected_balance)}</p></div><div className="flex items-center gap-2"><Badge row={row}/><ChevronDown className="h-4 w-4"/></div></button>{expanded === row.id && <div className="border-t border-cash-border p-4 font-body text-sm"><div className="grid grid-cols-2 gap-3"><p>Entradas <b className="block text-cash-positive">{cashMoney(entryTotal(row))}</b></p><p>Saídas <b className="block text-cash-alert">{cashMoney(exitTotal(row))}</b></p><p className="col-span-2">Máquinas / contas <b className="block">{row.machine_accounts || '—'}</b></p></div><div className="mt-4 flex justify-end gap-2"><Button variant="outline" onClick={() => onEdit(row)}><Pencil/> Editar</Button><Button variant="outline" onClick={() => onDelete(row)} className="text-cash-alert"><Trash2/> Excluir</Button></div></div>}</article>)}</div></>;
}