import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Pencil, Plus, Phone } from 'lucide-react';
import MachineRotationDialog from '@/components/relatorios/MachineRotationDialog';
import { brl } from '@/lib/financialReportUtils';
const days={segunda:'Segunda',terca:'Terça',quarta:'Quarta',quinta:'Quinta',sexta:'Sexta',sabado:'Sábado',domingo:'Domingo'};
export default function MachineRotationReport({records,onSaved}){
 const [open,setOpen]=useState(false),[editing,setEditing]=useState(null);const close=()=>{setOpen(false);setEditing(null)};
 return <div className="space-y-3"><div className="flex justify-end print:hidden"><Button onClick={()=>setOpen(true)}><Plus/>Novo rodízio</Button></div><div className="rounded-xl border bg-card overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-muted"><tr>{['Dia','Operadora','Máquina','Horário','Meta vendas','Meta transações','Gerente','Contato','Ação'].map(h=><th key={h} className="px-4 py-3 text-left font-medium">{h}</th>)}</tr></thead><tbody className="divide-y">{records.filter(x=>x.status==='ativo').map(x=><tr key={x.id}><td className="px-4 py-3 font-medium">{days[x.weekday]}</td><td className="px-4 py-3">{x.operator}</td><td className="px-4 py-3">{x.terminal}</td><td className="px-4 py-3">{x.start_time&&x.end_time?`${x.start_time}–${x.end_time}`:'—'}</td><td className="px-4 py-3">{brl(x.sales_goal)}</td><td className="px-4 py-3">{x.transaction_goal||0}</td><td className="px-4 py-3">{x.manager_name||'—'}</td><td className="px-4 py-3">{x.manager_phone?<a href={`tel:${x.manager_phone}`} className="inline-flex items-center gap-1 text-emerald-700"><Phone className="h-3 w-3"/>{x.manager_phone}</a>:'—'}</td><td className="px-4 py-3 print:hidden"><Button size="icon" variant="ghost" onClick={()=>{setEditing(x);setOpen(true)}}><Pencil/></Button></td></tr>)}{!records.length&&<tr><td colSpan="9" className="p-10 text-center text-muted-foreground">Nenhum rodízio cadastrado.</td></tr>}</tbody></table></div></div><MachineRotationDialog open={open} onClose={close} record={editing} onSaved={onSaved}/></div>;
}