import { useEffect, useState } from 'react';
import { base44 } from '@/api/base44Client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
const blank={weekday:'segunda',operator:'',terminal:'',sales_goal:0,transaction_goal:0,manager_name:'',manager_phone:'',start_time:'',end_time:'',status:'ativo',observation:''},cls='h-9 w-full rounded-md border bg-background px-3 text-sm';
export default function MachineRotationDialog({open,onClose,record,onSaved}){
 const [f,setF]=useState(blank),[saving,setSaving]=useState(false),[error,setError]=useState('');useEffect(()=>{if(open){setF(record?{...blank,...record}:blank);setError('')}},[open,record]);const set=(k,v)=>setF(x=>({...x,[k]:v}));
 const save=async()=>{if(!f.operator||!f.terminal){setError('Informe a operadora e a máquina.');return}setSaving(true);try{const payload={...f,sales_goal:Number(f.sales_goal||0),transaction_goal:Number(f.transaction_goal||0)};record?await base44.entities.MachineRotation.update(record.id,payload):await base44.entities.MachineRotation.create(payload);onClose();await onSaved()}catch(e){setError(e.message||'Não foi possível salvar.')}finally{setSaving(false)}};
 return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>{record?'Editar rodízio':'Novo rodízio de máquina'}</DialogTitle></DialogHeader><div className="grid sm:grid-cols-2 gap-3"><Field l="Dia da semana"><select className={cls} value={f.weekday} onChange={e=>set('weekday',e.target.value)}>{[['segunda','Segunda'],['terca','Terça'],['quarta','Quarta'],['quinta','Quinta'],['sexta','Sexta'],['sabado','Sábado'],['domingo','Domingo']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field l="Operadora *"><Input value={f.operator} onChange={e=>set('operator',e.target.value)}/></Field><Field l="Máquina/Terminal *"><Input value={f.terminal} onChange={e=>set('terminal',e.target.value)}/></Field><Field l="Meta de vendas"><Input type="number" value={f.sales_goal} onChange={e=>set('sales_goal',e.target.value)}/></Field><Field l="Meta de transações"><Input type="number" value={f.transaction_goal} onChange={e=>set('transaction_goal',e.target.value)}/></Field><Field l="Gerente"><Input value={f.manager_name} onChange={e=>set('manager_name',e.target.value)}/></Field><Field l="Contato direto do gerente"><Input type="tel" value={f.manager_phone} onChange={e=>set('manager_phone',e.target.value)}/></Field><Field l="Horário inicial"><Input type="time" value={f.start_time} onChange={e=>set('start_time',e.target.value)}/></Field><Field l="Horário final"><Input type="time" value={f.end_time} onChange={e=>set('end_time',e.target.value)}/></Field><Field l="Observação"><Input value={f.observation} onChange={e=>set('observation',e.target.value)}/></Field></div>{error&&<p className="text-sm text-destructive">{error}</p>}<DialogFooter><Button variant="outline" onClick={onClose}>Cancelar</Button><Button onClick={save} disabled={saving}>{saving?'Salvando...':'Salvar'}</Button></DialogFooter></DialogContent></Dialog>;
}
function Field({l,children}){return <div className="space-y-1"><Label className="text-xs">{l}</Label>{children}</div>}