import { useEffect, useMemo, useState } from 'react';
import { base44 } from '@/api/base44Client';
import { currentUserName } from '@/lib/useCurrentUser';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { Wallet, CreditCard, Bike, CheckCircle2, Plus, AlertTriangle, TrendingUp, TrendingDown, BarChart3 } from 'lucide-react';

const today=()=>new Date().toISOString().slice(0,10);
const brl=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const fmt=v=>v?String(v).slice(0,10).split('-').reverse().join('/'):'—';
const inputCls='h-9 w-full rounded-md border border-input bg-background px-3 text-sm';
const CHANNELS={loja:'Loja',delivery_proprio:'Delivery próprio',ifood:'iFood','99food':'99Food',brendi:'Brendi',whatsapp:'WhatsApp',outro:'Outro'};

export default function ReceitasFinanceiras(){
 const [tab,setTab]=useState('receitas'); const [open,setOpen]=useState(''); const [period,setPeriod]=useState(today().slice(0,7)); const [receivingId,setReceivingId]=useState('');
 const [data,setData]=useState({revenues:[],receivables:[],cards:[],delivery:[],reconciliations:[],accounts:[],expenses:[]});
 const load=async()=>{const [revenues,receivables,cards,delivery,reconciliations,accounts,expenses]=await Promise.all([
  base44.entities.Revenue.list('-date',1000).catch(()=>[]),base44.entities.AccountsReceivable.list('expected_date',1000).catch(()=>[]),base44.entities.CardReceivable.list('expected_date',1000).catch(()=>[]),base44.entities.DeliverySettlement.list('expected_date',500).catch(()=>[]),base44.entities.ManualReconciliation.list('-date',500).catch(()=>[]),base44.entities.FinancialAccount.list('name',200).catch(()=>[]),base44.entities.FinancialExpense.list('-date',1500).catch(()=>[])
 ]);setData({revenues,receivables,cards,delivery,reconciliations,accounts,expenses})};
 useEffect(()=>{load()},[]);
 const gross=data.revenues.filter(x=>x.status!=='cancelado').reduce((s,x)=>s+Number(x.gross_amount||0),0);
 const net=data.revenues.filter(x=>x.status!=='cancelado').reduce((s,x)=>s+Number(x.net_amount||0),0);
 const pending=data.receivables.filter(x=>!['recebido','cancelado'].includes(x.status)).reduce((s,x)=>s+Number(x.net_amount||0),0);
 const divergent=data.reconciliations.filter(x=>x.status==='divergente').length;
 const confirmReceipt=async(x)=>{if(receivingId)return;setReceivingId(x.id);try{const receivedDate=today();await base44.entities.AccountsReceivable.update(x.id,{status:'recebido',received_date:receivedDate,reconciled:false,responsible_user:currentUserName()});if(x.source_type==='cartao'&&x.source_id){await base44.entities.CardReceivable.update(x.source_id,{status:'recebido',received_date:receivedDate})}if(x.source_type==='delivery'&&x.source_id){await base44.entities.DeliverySettlement.update(x.source_id,{status:'recebido',received_date:receivedDate})}await load()}finally{setReceivingId('')}};
 const monthly=useMemo(()=>buildMonthlySummary(data,period),[data,period]);
 return <div className="space-y-5">
  <div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-semibold">Receitas & Conciliação</h1><p className="text-sm text-slate-500">Controle manual de vendas, cartões, repasses e recebimentos</p></div><Button onClick={()=>setOpen('receita')} className="gap-2"><Plus className="w-4 h-4"/> Nova receita</Button></div>
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Stat label="Receita bruta" value={brl(gross)} icon={Wallet}/><Stat label="Receita líquida" value={brl(net)} icon={CheckCircle2}/><Stat label="A receber" value={brl(pending)} icon={CreditCard} danger={pending>0}/><Stat label="Divergências" value={divergent} icon={AlertTriangle} danger={divergent>0}/></div>
  <div className="flex gap-1 overflow-x-auto">{[['receitas','Receitas'],['receber','A receber'],['cartoes','Cartões'],['delivery','Delivery'],['conciliacao','Conciliação'],['fluxo','Fluxo de Caixa'],['dre','DRE']].map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`px-3.5 py-2 rounded-lg text-sm font-medium whitespace-nowrap ${tab===k?'bg-slate-900 text-white':'bg-slate-100 text-slate-600'}`}>{l}</button>)}</div>
  {tab==='receitas'&&<SimpleTable headers={['Data','Descrição','Canal','Forma','Bruto','Taxas','Líquido','Status']} rows={data.revenues.map(x=>[fmt(x.date),x.description,CHANNELS[x.source_type]||x.source_type,x.payment_method,brl(x.gross_amount),brl(x.fee_amount),brl(x.net_amount),x.status])}/>} 
  {tab==='receber'&&<><div className="flex justify-end"><Button variant="outline" onClick={()=>setOpen('receber')} className="gap-2"><Plus className="w-4 h-4"/> Nova conta a receber</Button></div><SimpleTable headers={['Previsto','Descrição','Origem','Bruto','Taxas','Líquido','Conta','Status','Ação']} rows={data.receivables.map(x=>[fmt(x.expected_date),x.description,x.source_type,brl(x.gross_amount),brl(x.fee_amount),brl(x.net_amount),x.financial_account_name||'—',x.status,!['recebido','cancelado'].includes(x.status)?<Button key={`rec-${x.id}`} size="sm" variant="outline" disabled={receivingId===x.id} onClick={()=>confirmReceipt(x)}>{receivingId===x.id?'Recebendo...':'Confirmar recebimento'}</Button>:<span key={`ok-${x.id}`} className="text-emerald-700 font-medium">Recebido ✓</span>])}/></>}
  {tab==='cartoes'&&<><div className="flex justify-end"><Button variant="outline" onClick={()=>setOpen('cartao')} className="gap-2"><Plus className="w-4 h-4"/> Lançar cartão</Button></div><SimpleTable headers={['Venda','Adquirente','Máquina','Tipo','Bruto','Taxa','Líquido','Previsto','Status']} rows={data.cards.map(x=>[fmt(x.sale_date),x.acquirer,x.terminal||'—',x.payment_type,brl(x.gross_amount),brl(x.fee_amount),brl(x.net_amount),fmt(x.expected_date),x.status])}/></>}
  {tab==='delivery'&&<><div className="flex justify-end"><Button variant="outline" onClick={()=>setOpen('delivery')} className="gap-2"><Plus className="w-4 h-4"/> Lançar repasse</Button></div><SimpleTable headers={['Período','Canal','Pedidos','Bruto','Comissões/Taxas','Líquido','Previsto','Status']} rows={data.delivery.map(x=>[`${fmt(x.reference_start)} a ${fmt(x.reference_end)}`,CHANNELS[x.channel]||x.channel,x.orders_count||0,brl(x.gross_amount),brl(Number(x.commission_amount||0)+Number(x.delivery_fee_amount||0)+Number(x.other_fee_amount||0)),brl(x.net_amount),fmt(x.expected_date),x.status])}/></>}
  {tab==='conciliacao'&&<><div className="flex justify-end"><Button variant="outline" onClick={()=>setOpen('conciliacao')} className="gap-2"><Plus className="w-4 h-4"/> Nova conferência</Button></div><SimpleTable headers={['Data','Referência','Esperado','Encontrado','Diferença','Conta','Status']} rows={data.reconciliations.map(x=>[fmt(x.date),x.reference_description||x.reference_type,brl(x.expected_amount),brl(x.actual_amount),brl(x.difference),x.financial_account_name||'—',x.status])}/></>}
  {tab==='fluxo'&&<CashFlowPanel period={period} setPeriod={setPeriod} summary={monthly}/>} 
  {tab==='dre'&&<DrePanel period={period} setPeriod={setPeriod} summary={monthly}/>} 
  <EntryDialog type={open} open={!!open} onClose={()=>setOpen('')} data={data} onSaved={load}/>
 </div>
}
function Stat({label,value,icon:Icon,danger}){return <div className={`rounded-xl border p-4 ${danger?'border-amber-200 bg-amber-50':'bg-white'}`}><p className="text-xs text-slate-500">{label}</p><div className="flex justify-between items-end"><p className="text-xl font-semibold mt-1">{value}</p><Icon className="w-5 h-5 text-amber-600"/></div></div>}
function SimpleTable({headers,rows}){return <div className="rounded-xl border bg-white overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm min-w-[850px]"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{headers.map(h=><th key={h} className="px-4 py-3 text-left font-medium">{h}</th>)}</tr></thead><tbody className="divide-y">{rows.length?rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j} className={`px-4 py-3 ${j===0||j===1?'font-medium':''}`}>{v}</td>)}</tr>):<tr><td colSpan={headers.length} className="p-10 text-center text-slate-400">Nenhum registro.</td></tr>}</tbody></table></div></div>}
function EntryDialog({type,open,onClose,data,onSaved}){
 const [f,setF]=useState({}); const set=(k,v)=>setF(x=>({...x,[k]:v})); useEffect(()=>{if(open)setF({date:today(),sale_date:today(),reference_start:today(),reference_end:today(),reference_date:today(),expected_date:today(),gross_amount:'',fee_amount:'0',net_amount:'',source_type:'loja',payment_method:'pix',channel:'ifood',acquirer:'',terminal:'',payment_type:'debito',orders_count:'0',actual_amount:'',expected_amount:'',reference_type:'outro',reference_description:'',financial_account_id:''})},[open,type]);
 const account=data.accounts.find(x=>x.id===f.financial_account_id); const autoNet=()=>Number(f.net_amount||Number(f.gross_amount||0)-Number(f.fee_amount||0));
 const save=async()=>{if(type==='receita'){await base44.entities.Revenue.create({...f,gross_amount:Number(f.gross_amount||0),fee_amount:Number(f.fee_amount||0),net_amount:autoNet(),financial_account_name:account?.name||'',origin_mode:'manual',responsible_user:currentUserName(),description:f.description||'Receita manual',status:f.status||'recebido'})}
 else if(type==='receber'){await base44.entities.AccountsReceivable.create({...f,description:f.description||'Conta a receber',gross_amount:Number(f.gross_amount||0),fee_amount:Number(f.fee_amount||0),net_amount:autoNet(),financial_account_name:account?.name||'',responsible_user:currentUserName(),status:'pendente'})}
 else if(type==='cartao'){const card=await base44.entities.CardReceivable.create({...f,gross_amount:Number(f.gross_amount||0),fee_amount:Number(f.fee_amount||0),net_amount:autoNet(),financial_account_name:account?.name||'',origin_mode:'manual',responsible_user:currentUserName(),status:'a_receber'});const ar=await base44.entities.AccountsReceivable.create({description:`Cartão ${f.acquirer||''}`,source_type:'cartao',source_id:card.id,reference_date:f.sale_date,expected_date:f.expected_date,gross_amount:Number(f.gross_amount||0),fee_amount:Number(f.fee_amount||0),net_amount:autoNet(),financial_account_id:f.financial_account_id||'',financial_account_name:account?.name||'',status:'pendente',responsible_user:currentUserName()});await base44.entities.CardReceivable.update(card.id,{accounts_receivable_id:ar.id})}
 else if(type==='delivery'){const fees=Number(f.commission_amount||0)+Number(f.delivery_fee_amount||0)+Number(f.other_fee_amount||0)+Number(f.discount_amount||0);const net=Number(f.net_amount||Number(f.gross_amount||0)-fees);const rep=await base44.entities.DeliverySettlement.create({...f,orders_count:Number(f.orders_count||0),gross_amount:Number(f.gross_amount||0),discount_amount:Number(f.discount_amount||0),commission_amount:Number(f.commission_amount||0),delivery_fee_amount:Number(f.delivery_fee_amount||0),other_fee_amount:Number(f.other_fee_amount||0),net_amount:net,financial_account_name:account?.name||'',origin_mode:'manual',responsible_user:currentUserName(),status:'a_receber'});const ar=await base44.entities.AccountsReceivable.create({description:`Repasse ${CHANNELS[f.channel]||f.channel}`,source_type:'delivery',source_id:rep.id,reference_date:f.reference_end,expected_date:f.expected_date,gross_amount:Number(f.gross_amount||0),fee_amount:fees,net_amount:net,financial_account_id:f.financial_account_id||'',financial_account_name:account?.name||'',status:'pendente',responsible_user:currentUserName()});await base44.entities.DeliverySettlement.update(rep.id,{accounts_receivable_id:ar.id})}
 else if(type==='conciliacao'){const diff=Number(f.actual_amount||0)-Number(f.expected_amount||0);await base44.entities.ManualReconciliation.create({date:f.date,reference_type:f.reference_type,reference_description:f.reference_description,expected_amount:Number(f.expected_amount||0),actual_amount:Number(f.actual_amount||0),difference:diff,financial_account_id:f.financial_account_id||'',financial_account_name:account?.name||'',status:Math.abs(diff)<0.01?'conciliado':'divergente',responsible_user:currentUserName()})}onClose();await onSaved()};
 const title={receita:'Nova receita',receber:'Nova conta a receber',cartao:'Lançar recebível de cartão',delivery:'Lançar repasse de delivery',conciliacao:'Conciliação manual'}[type]||'';
 return <Dialog open={open} onOpenChange={o=>!o&&onClose()}><DialogContent className="max-w-xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{title}</DialogTitle></DialogHeader><div className="grid sm:grid-cols-2 gap-3">
 {type==='receita'&&<><Field l="Data"><Input type="date" value={f.date||''} onChange={e=>set('date',e.target.value)}/></Field><Field l="Descrição"><Input value={f.description||''} onChange={e=>set('description',e.target.value)}/></Field><Field l="Canal"><Select v={f.source_type} on={v=>set('source_type',v)} opts={Object.entries(CHANNELS)}/></Field><Field l="Forma"><Input value={f.payment_method||''} onChange={e=>set('payment_method',e.target.value)}/></Field></>}
 {type==='receber'&&<><Field l="Descrição"><Input value={f.description||''} onChange={e=>set('description',e.target.value)}/></Field><Field l="Previsão"><Input type="date" value={f.expected_date||''} onChange={e=>set('expected_date',e.target.value)}/></Field></>}
 {type==='cartao'&&<><Field l="Data da venda"><Input type="date" value={f.sale_date||''} onChange={e=>set('sale_date',e.target.value)}/></Field><Field l="Adquirente"><Input value={f.acquirer||''} onChange={e=>set('acquirer',e.target.value)} placeholder="Stone, Mercado Pago, Itaú..."/></Field><Field l="Maquininha"><Input value={f.terminal||''} onChange={e=>set('terminal',e.target.value)}/></Field><Field l="Previsão"><Input type="date" value={f.expected_date||''} onChange={e=>set('expected_date',e.target.value)}/></Field></>}
 {type==='delivery'&&<><Field l="Início"><Input type="date" value={f.reference_start||''} onChange={e=>set('reference_start',e.target.value)}/></Field><Field l="Fim"><Input type="date" value={f.reference_end||''} onChange={e=>set('reference_end',e.target.value)}/></Field><Field l="Canal"><Select v={f.channel} on={v=>set('channel',v)} opts={Object.entries(CHANNELS).filter(([k])=>['ifood','99food','brendi','delivery_proprio','outro'].includes(k))}/></Field><Field l="Pedidos"><Input type="number" value={f.orders_count||''} onChange={e=>set('orders_count',e.target.value)}/></Field><Field l="Previsão de repasse"><Input type="date" value={f.expected_date||''} onChange={e=>set('expected_date',e.target.value)}/></Field></>}
 {type==='conciliacao'?<><Field l="Data"><Input type="date" value={f.date||''} onChange={e=>set('date',e.target.value)}/></Field><Field l="Referência"><Input value={f.reference_description||''} onChange={e=>set('reference_description',e.target.value)}/></Field><Field l="Esperado"><Input type="number" value={f.expected_amount||''} onChange={e=>set('expected_amount',e.target.value)}/></Field><Field l="Encontrado"><Input type="number" value={f.actual_amount||''} onChange={e=>set('actual_amount',e.target.value)}/></Field></>:<><Field l="Valor bruto"><Input type="number" value={f.gross_amount||''} onChange={e=>set('gross_amount',e.target.value)}/></Field><Field l="Taxas/Comissões"><Input type="number" value={f.fee_amount||''} onChange={e=>set('fee_amount',e.target.value)}/></Field>{type==='delivery'&&<><Field l="Comissão"><Input type="number" value={f.commission_amount||''} onChange={e=>set('commission_amount',e.target.value)}/></Field><Field l="Taxa entrega"><Input type="number" value={f.delivery_fee_amount||''} onChange={e=>set('delivery_fee_amount',e.target.value)}/></Field></>}<Field l="Valor líquido"><Input type="number" value={f.net_amount||''} onChange={e=>set('net_amount',e.target.value)}/></Field></>}
 <Field l="Conta de destino"><select className={inputCls} value={f.financial_account_id||''} onChange={e=>set('financial_account_id',e.target.value)}><option value="">Não informada</option>{data.accounts.filter(x=>x.status==='ativo').map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field>
 </div><DialogFooter><Button variant="outline" onClick={onClose}>Cancelar</Button><Button onClick={save}>Salvar</Button></DialogFooter></DialogContent></Dialog>
}
function buildMonthlySummary(data,period){
 const inPeriod=v=>String(v||'').slice(0,7)===period;
 const revenues=data.revenues.filter(x=>x.status!=='cancelado'&&inPeriod(x.date));
 const cards=data.cards.filter(x=>x.status!=='cancelado'&&inPeriod(x.sale_date));
 const delivery=data.delivery.filter(x=>x.status!=='cancelado'&&inPeriod(x.reference_end||x.reference_start));
 const expenses=data.expenses.filter(x=>x.status!=='cancelado'&&inPeriod(x.date));
 const receivedRevenue=data.revenues.filter(x=>x.status==='recebido'&&inPeriod(x.received_date||x.date));
 const receivedAr=data.receivables.filter(x=>x.status==='recebido'&&inPeriod(x.received_date));
 const paidExpenses=data.expenses.filter(x=>x.status==='pago'&&inPeriod(x.paid_date||x.date));
 const gross=revenues.reduce((s,x)=>s+Number(x.gross_amount||0),0)+cards.reduce((s,x)=>s+Number(x.gross_amount||0),0)+delivery.reduce((s,x)=>s+Number(x.gross_amount||0),0);
 const fees=revenues.reduce((s,x)=>s+Number(x.fee_amount||0),0)+cards.reduce((s,x)=>s+Number(x.fee_amount||0),0)+delivery.reduce((s,x)=>s+Number(x.discount_amount||0)+Number(x.commission_amount||0)+Number(x.delivery_fee_amount||0)+Number(x.other_fee_amount||0),0);
 const netRevenue=gross-fees;
 const expenseTotal=expenses.reduce((s,x)=>s+Number(x.amount||0),0);
 const entries=receivedRevenue.reduce((s,x)=>s+Number(x.net_amount||0),0)+receivedAr.reduce((s,x)=>s+Number(x.net_amount||0),0);
 const exits=paidExpenses.reduce((s,x)=>s+Number(x.amount||0),0);
 const byCategory={};expenses.forEach(x=>{const k=x.category_name||x.classification||'Sem categoria';byCategory[k]=(byCategory[k]||0)+Number(x.amount||0)});
 const movementRows=[
  ...receivedRevenue.map(x=>({date:x.received_date||x.date,description:x.description||'Receita',type:'Entrada',amount:Number(x.net_amount||0),account:x.financial_account_name||'—'})),
  ...receivedAr.map(x=>({date:x.received_date,description:x.description||'Recebimento',type:'Entrada',amount:Number(x.net_amount||0),account:x.financial_account_name||'—'})),
  ...paidExpenses.map(x=>({date:x.paid_date||x.date,description:x.description||'Despesa',type:'Saída',amount:-Number(x.amount||0),account:x.account||x.financial_account_name||'—'})),
 ].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));
 return {gross,fees,netRevenue,expenseTotal,result:netRevenue-expenseTotal,entries,exits,cashBalance:entries-exits,byCategory,movementRows};
}
function PeriodControl({period,setPeriod}){return <div className="flex items-end gap-2"><div><Label className="text-xs">Mês</Label><Input type="month" value={period} onChange={e=>setPeriod(e.target.value)} className="w-40"/></div></div>}
function CashFlowPanel({period,setPeriod,summary}){return <div className="space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="font-semibold text-slate-900">Fluxo de Caixa</h3><p className="text-sm text-slate-500">Entradas efetivamente recebidas e saídas efetivamente pagas.</p></div><PeriodControl period={period} setPeriod={setPeriod}/></div><div className="grid grid-cols-2 lg:grid-cols-3 gap-3"><Stat label="Entradas recebidas" value={brl(summary.entries)} icon={TrendingUp}/><Stat label="Saídas pagas" value={brl(summary.exits)} icon={TrendingDown} danger={summary.exits>summary.entries}/><Stat label="Saldo do mês" value={brl(summary.cashBalance)} icon={Wallet} danger={summary.cashBalance<0}/></div><SimpleTable headers={['Data','Descrição','Movimento','Conta','Valor']} rows={summary.movementRows.map(x=>[fmt(x.date),x.description,x.type,x.account,<span key={`${x.date}-${x.description}-${x.amount}`} className={x.amount<0?'text-rose-700 font-semibold':'text-emerald-700 font-semibold'}>{brl(x.amount)}</span>])}/></div>}
function DrePanel({period,setPeriod,summary}){const cats=Object.entries(summary.byCategory).sort((a,b)=>b[1]-a[1]);return <div className="space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="font-semibold text-slate-900">DRE Gerencial</h3><p className="text-sm text-slate-500">Visão mensal por competência com faturamento, taxas, despesas e resultado estimado.</p></div><PeriodControl period={period} setPeriod={setPeriod}/></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Stat label="Faturamento bruto" value={brl(summary.gross)} icon={BarChart3}/><Stat label="Taxas e comissões" value={brl(summary.fees)} icon={TrendingDown}/><Stat label="Despesas" value={brl(summary.expenseTotal)} icon={Wallet}/><Stat label="Resultado estimado" value={brl(summary.result)} icon={TrendingUp} danger={summary.result<0}/></div><div className="grid lg:grid-cols-2 gap-4"><div className="rounded-xl border bg-white p-4"><h4 className="font-semibold mb-3">Demonstrativo</h4>{[['Faturamento bruto',summary.gross],['(-) Taxas e comissões',-summary.fees],['(=) Receita líquida',summary.netRevenue],['(-) Despesas operacionais',-summary.expenseTotal],['(=) Resultado estimado',summary.result]].map(([l,v],i)=><div key={l} className={`flex justify-between py-2 text-sm ${i===4?'border-t mt-1 pt-3 font-semibold':'border-b'}`}><span>{l}</span><span className={v<0?'text-rose-700':''}>{brl(v)}</span></div>)}</div><div className="rounded-xl border bg-white p-4"><h4 className="font-semibold mb-3">Despesas por categoria</h4>{cats.length?cats.map(([k,v])=><div key={k} className="flex justify-between py-2 border-b text-sm"><span>{k}</span><strong>{brl(v)}</strong></div>):<p className="text-sm text-slate-400">Sem despesas no período.</p>}</div></div></div>}
function Field({l,children}){return <div className="space-y-1"><Label className="text-xs">{l}</Label>{children}</div>}
function Select({v,on,opts}){return <select className={inputCls} value={v||''} onChange={e=>on(e.target.value)}>{opts.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select>}
