import { useEffect, useMemo, useState } from 'react';
import { base44 } from '@/api/base44Client';
import { useUserRole } from '@/lib/useUserRole';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Download, Printer } from 'lucide-react';
import FinancialSummary from '@/components/relatorios/FinancialSummary';
import AccountsReport from '@/components/relatorios/AccountsReport';
import ReconciliationReport from '@/components/relatorios/ReconciliationReport';
import MachineRotationReport from '@/components/relatorios/MachineRotationReport';
import { exportFinancialCsv } from '@/lib/financialReportUtils';
const today=()=>new Date().toISOString().slice(0,10),month=()=>today().slice(0,7),empty={revenues:[],expenses:[],payables:[],receivables:[],cards:[],delivery:[],reconciliations:[],rotations:[]};
export default function RelatorioFinanceiro(){
 const {isAdmin}=useUserRole(),[data,setData]=useState(empty),[mode,setMode]=useState('month'),[selectedMonth,setSelectedMonth]=useState(month()),[start,setStart]=useState(`${month()}-01`),[end,setEnd]=useState(today()),[tab,setTab]=useState('resumo'),[loading,setLoading]=useState(true);
 const range=mode==='month'?{start:`${selectedMonth}-01`,end:`${selectedMonth}-31`}:{start,end};
 const load=async()=>{setLoading(true);const values=await Promise.all(['Revenue','FinancialExpense','AccountsPayable','AccountsReceivable','CardReceivable','DeliverySettlement','ManualReconciliation','MachineRotation'].map(name=>base44.entities[name].list('-created_date',1500)));setData(Object.fromEntries(Object.keys(empty).map((k,i)=>[k,values[i]])));setLoading(false)};useEffect(()=>{if(isAdmin)load()},[isAdmin]);
 const filtered=useMemo(()=>{const inRange=d=>d>=range.start&&d<=range.end;return {...data,revenues:data.revenues.filter(x=>inRange(x.date)),expenses:data.expenses.filter(x=>inRange(x.date)),payables:data.payables.filter(x=>inRange(x.due_date)),receivables:data.receivables.filter(x=>inRange(x.expected_date)),cards:data.cards.filter(x=>inRange(x.sale_date)),delivery:data.delivery.filter(x=>inRange(x.reference_end||x.reference_start)),reconciliations:data.reconciliations.filter(x=>inRange(x.date))}},[data,range.start,range.end]);
 if(!isAdmin)return <div className="rounded-xl border bg-card p-10 text-center"><h1 className="text-xl font-semibold">Acesso restrito</h1><p className="mt-2 text-muted-foreground">Este relatório contém dados financeiros e exige permissão de administrador.</p></div>;
 return <div className="space-y-5" id="financial-report"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold">Relatório Financeiro</h1><p className="text-sm text-muted-foreground">Resumo, vencimentos, conciliações e rodízio de máquinas</p></div><div className="flex gap-2 print:hidden"><Button variant="outline" onClick={()=>exportFinancialCsv(filtered,range.start,range.end)}><Download/>Exportar</Button><Button onClick={()=>window.print()}><Printer/>Imprimir</Button></div></div><div className="flex flex-wrap items-end gap-3 rounded-xl border bg-card p-4 print:hidden"><label className="text-xs">Período<select className="ml-2 h-9 rounded-md border bg-background px-3 text-sm" value={mode} onChange={e=>setMode(e.target.value)}><option value="month">Mensal</option><option value="custom">Datas personalizadas</option></select></label>{mode==='month'?<label className="text-xs">Mês<Input type="month" value={selectedMonth} onChange={e=>setSelectedMonth(e.target.value)} className="mt-1 w-44"/></label>:<><label className="text-xs">Data inicial<Input type="date" value={start} onChange={e=>setStart(e.target.value)} className="mt-1 w-44"/></label><label className="text-xs">Data final<Input type="date" value={end} onChange={e=>setEnd(e.target.value)} className="mt-1 w-44"/></label></>}</div><div className="flex gap-1 overflow-x-auto print:hidden">{[['resumo','Resumo'],['contas','Contas e vencimentos'],['conciliacoes','Conciliações'],['rodizio','Rodízio de máquinas']].map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`whitespace-nowrap rounded-lg px-3.5 py-2 text-sm font-medium ${tab===k?'bg-primary text-primary-foreground':'bg-muted text-muted-foreground'}`}>{l}</button>)}</div>{loading?<div className="py-16 text-center text-muted-foreground">Carregando relatório...</div>:<>{tab==='resumo'&&<FinancialSummary data={filtered}/>} {tab==='contas'&&<AccountsReport payables={filtered.payables} receivables={filtered.receivables}/>} {tab==='conciliacoes'&&<ReconciliationReport cards={filtered.cards} delivery={filtered.delivery} reconciliations={filtered.reconciliations}/>} {tab==='rodizio'&&<MachineRotationReport records={filtered.rotations} onSaved={load}/>}</>}</div>;
}